import type { ColorPalette, ThemeFonts, ThemeStrings, ThemeSounds } from '../types';

export const DEFAULT_FONTS: ThemeFonts = {
  score: 'system-ui, -apple-system, "Segoe UI", sans-serif',
  label: 'system-ui, -apple-system, "Segoe UI", sans-serif',
  title: 'system-ui, -apple-system, "Segoe UI", sans-serif',
};

export const DEFAULT_STRINGS: ThemeStrings = {
  title: 'PINBALL',
  subtitle: 'GET THE HIGH SCORE!',
  pressStart: 'PRESS SPACE OR ENTER',
  pressStartTouch: 'TAP TO START',
  gameOver: 'GAME OVER',
  playAgain: 'PRESS SPACE TO PLAY AGAIN',
  playAgainTouch: 'TAP TO PLAY AGAIN',
  pull: 'PULL',
  controls: [
    'Z or \u2190 = LEFT FLIPPER',
    '/ or \u2192 = RIGHT FLIPPER',
    'SPACE = PLUNGER',
    'F = SWAP THEME',
  ],
  controlsTouch: [
    'TAP LEFT = LEFT FLIPPER',
    'TAP RIGHT = RIGHT FLIPPER',
    'HOLD & RELEASE CENTER = LAUNCH',
    'TAP TOP = SWAP THEME',
  ],
};

export const PALETTE_PRESETS = {
  /** Cool blue/cyan dark base. Suits arcade, sci-fi, retro-terminal aesthetics. */
  dark: {
    background: '#0a0a1a',
    tableFill: '#0b1523',
    tableBorder: '#1e3a5f',
    ballColor: '#b0b8c8',
    ballHighlight: '#e8f0ff',
    flipperColor: '#1a44aa',
    flipperActiveColor: '#3388ff',
    bumperIdleColor: '#112244',
    bumperLitColor: '#ff6600',
    bumperBorderColor: '#2255bb',
    bumperLitBorderColor: '#ffaa22',
    dropTargetColor: '#22ccff',
    dropTargetDownColor: '#113355',
    wallColor: '#1e3a5f',
    plungerTrackColor: '#080f1a',
    plungerColor: '#556677',
    plungerChargedColor: '#ff3322',
    scoreColor: '#00ff99',
    hudBackground: 'rgba(0, 0, 0, 0.65)',
    labelColor: '#8899cc',
    drainColor: 'rgba(180, 0, 0, 0.35)',
    guideColor: '#0d2040',
    slingshotColor: '#22ccff',
    slingshotLitColor: '#66eeff',
    rolloverColor: '#4488aa',
    rolloverLitColor: '#00ff99',
    scoopColor: '#334466',
    scoopLitColor: '#00ffcc',
    lockIndicatorColor: '#00ff99',
    orbitRailColor: '#1a5577',
    overlay: 'rgba(0, 0, 20, 0.78)',
    accent: '#00ffcc',
  } satisfies ColorPalette,
  /** Soft pink/pastel base. Suits dreamy, kawaii, candy aesthetics. */
  pastel: {
    background: '#fff0f5',
    tableFill: '#fce4ec',
    tableBorder: '#f48fb1',
    ballColor: '#ffffff',
    ballHighlight: '#fff9c4',
    flipperColor: '#e91e90',
    flipperActiveColor: '#ff69b4',
    bumperIdleColor: '#fce4ec',
    bumperLitColor: '#ff80ab',
    bumperBorderColor: '#f48fb1',
    bumperLitBorderColor: '#ff4081',
    dropTargetColor: '#f06292',
    dropTargetDownColor: '#f8bbd0',
    wallColor: '#f48fb1',
    plungerTrackColor: '#fce4ec',
    plungerColor: '#e91e90',
    plungerChargedColor: '#ff4081',
    scoreColor: '#ad1457',
    hudBackground: 'rgba(252, 228, 236, 0.80)',
    labelColor: '#c2185b',
    drainColor: 'rgba(233, 30, 99, 0.20)',
    guideColor: '#f8bbd0',
    slingshotColor: '#f06292',
    slingshotLitColor: '#ff80ab',
    rolloverColor: '#f48fb1',
    rolloverLitColor: '#ff4081',
    scoopColor: '#f8bbd0',
    scoopLitColor: '#ff80ab',
    lockIndicatorColor: '#ff4081',
    orbitRailColor: '#f48fb1',
    overlay: 'rgba(252, 228, 236, 0.85)',
    accent: '#e91e63',
  } satisfies ColorPalette,
} as const;

/**
 * Pre-built sound bundles. Spread one into a theme's `sounds`, then override
 * individual events to taste. Each bundle is a complete `ThemeSounds` map.
 */
export const SOUND_MOODS = {
  /** Punchy arcade beeps — square/triangle/sawtooth, bright frequencies. */
  arcade: {
    bumper:          { type: 'synth', freq: 620, durationMs: 80,  wave: 'square',   volume: 0.15 },
    flipper:         { type: 'synth', freq: 180, durationMs: 45,  wave: 'triangle', volume: 0.12 },
    launch:          { type: 'synth', freq: 240, durationMs: 200, wave: 'sawtooth', volume: 0.15, slide: 540 },
    drain:           { type: 'synth', freq: 380, durationMs: 350, wave: 'sawtooth', volume: 0.2,  slide: -320 },
    dropTarget:      { type: 'synth', freq: 880, durationMs: 60,  wave: 'square',   volume: 0.18 },
    slingshot:       { type: 'synth', freq: 520, durationMs: 60,  wave: 'triangle', volume: 0.14 },
    rollover:        { type: 'synth', freq: 1200, durationMs: 40, wave: 'sine',     volume: 0.10 },
    lockBall:        { type: 'synth', freq: 330, durationMs: 300, wave: 'square',   volume: 0.18, slide: 220 },
    orbitShot:       { type: 'synth', freq: 300, durationMs: 400, wave: 'sine',     volume: 0.16, slide: 500 },
    missionComplete: { type: 'synth', freq: 440, durationMs: 550, wave: 'square',   volume: 0.22, slide: 660 },
    gameOver:        { type: 'synth', freq: 220, durationMs: 700, wave: 'sawtooth', volume: 0.22, slide: -180 },
  } satisfies ThemeSounds,
  /** Higher-pitched terminal beeps — dense square waves, longer slides. */
  chiptune: {
    bumper:          { type: 'synth', freq: 1040, durationMs: 50,  wave: 'square',   volume: 0.14 },
    flipper:         { type: 'synth', freq: 90,   durationMs: 40,  wave: 'square',   volume: 0.12 },
    launch:          { type: 'synth', freq: 120,  durationMs: 280, wave: 'sawtooth', volume: 0.18, slide: 680 },
    drain:           { type: 'synth', freq: 420,  durationMs: 400, wave: 'sawtooth', volume: 0.22, slide: -400 },
    dropTarget:      { type: 'synth', freq: 1200, durationMs: 55,  wave: 'triangle', volume: 0.16 },
    slingshot:       { type: 'synth', freq: 700,  durationMs: 50,  wave: 'square',   volume: 0.14 },
    rollover:        { type: 'synth', freq: 1500, durationMs: 35,  wave: 'sine',     volume: 0.10 },
    lockBall:        { type: 'synth', freq: 280,  durationMs: 350, wave: 'square',   volume: 0.20, slide: 180 },
    orbitShot:       { type: 'synth', freq: 250,  durationMs: 450, wave: 'sine',     volume: 0.18, slide: 400 },
    missionComplete: { type: 'synth', freq: 520,  durationMs: 650, wave: 'square',   volume: 0.24, slide: 880 },
    gameOver:        { type: 'synth', freq: 180,  durationMs: 900, wave: 'sawtooth', volume: 0.24, slide: -140 },
  } satisfies ThemeSounds,
  /** Soft bell-like sines, low volume, gentle upward slides. */
  dreamy: {
    bumper:          { type: 'synth', freq: 880,  durationMs: 120, wave: 'sine', volume: 0.08, slide: 440 },
    flipper:         { type: 'synth', freq: 330,  durationMs: 60,  wave: 'sine', volume: 0.07 },
    launch:          { type: 'synth', freq: 440,  durationMs: 300, wave: 'sine', volume: 0.10, slide: 880 },
    drain:           { type: 'synth', freq: 660,  durationMs: 500, wave: 'sine', volume: 0.10, slide: -330 },
    dropTarget:      { type: 'synth', freq: 1047, durationMs: 100, wave: 'sine', volume: 0.09, slide: 523 },
    slingshot:       { type: 'synth', freq: 784,  durationMs: 80,  wave: 'sine', volume: 0.08, slide: 392 },
    rollover:        { type: 'synth', freq: 1319, durationMs: 80,  wave: 'sine', volume: 0.06, slide: 660 },
    lockBall:        { type: 'synth', freq: 523,  durationMs: 400, wave: 'sine', volume: 0.10, slide: 262 },
    orbitShot:       { type: 'synth', freq: 660,  durationMs: 500, wave: 'sine', volume: 0.09, slide: 1320 },
    missionComplete: { type: 'synth', freq: 523,  durationMs: 700, wave: 'sine', volume: 0.12, slide: 1047 },
    gameOver:        { type: 'synth', freq: 440,  durationMs: 900, wave: 'sine', volume: 0.12, slide: -220 },
  } satisfies ThemeSounds,
  /** Low rumbling sawtooths, downward slides, demonic. */
  horror: {
    bumper:          { type: 'synth', freq: 80,   durationMs: 200,  wave: 'sawtooth', volume: 0.20, slide: -40 },
    flipper:         { type: 'synth', freq: 55,   durationMs: 80,   wave: 'sawtooth', volume: 0.15 },
    launch:          { type: 'synth', freq: 60,   durationMs: 500,  wave: 'sawtooth', volume: 0.22, slide: 200 },
    drain:           { type: 'synth', freq: 120,  durationMs: 800,  wave: 'sawtooth', volume: 0.25, slide: -100 },
    dropTarget:      { type: 'synth', freq: 150,  durationMs: 120,  wave: 'square',   volume: 0.20, slide: -80 },
    slingshot:       { type: 'synth', freq: 100,  durationMs: 100,  wave: 'sawtooth', volume: 0.18, slide: -50 },
    rollover:        { type: 'synth', freq: 200,  durationMs: 150,  wave: 'square',   volume: 0.12, slide: -100 },
    lockBall:        { type: 'synth', freq: 70,   durationMs: 600,  wave: 'sawtooth', volume: 0.24, slide: 50 },
    orbitShot:       { type: 'synth', freq: 90,   durationMs: 700,  wave: 'sawtooth', volume: 0.20, slide: -30 },
    missionComplete: { type: 'synth', freq: 110,  durationMs: 800,  wave: 'square',   volume: 0.25, slide: -60 },
    gameOver:        { type: 'synth', freq: 50,   durationMs: 1200, wave: 'sawtooth', volume: 0.28, slide: -30 },
  } satisfies ThemeSounds,
} as const;
